services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      # ИЗМЕНЕНИЕ: Указываем путь к файлу SQLite
      - DATABASE_URL=sqlite:///./dataset_platform.db
      - GROQ_API_KEY=${GROQ_API_KEY}
    # Удален depends_on, так как базы данных как отдельного сервиса больше нет
    volumes:
       # (Опционально) Чтобы база данных сохранялась при перезапуске контейнера
       - ./dataset_platform.db:/app/dataset_platform.db

  # Сервис db (Postgres) полностью удален